#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: getapp-storage
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Delete
#  hostPath:
#  # using Docker Desktop Volume "getmap-store" for testing purposes:
#    #path: "/var/lib/docker/volumes/getmap-store/"
#    #path: "/K8s_host/getmap-store/"
#    path: "/tmp"
#
