apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: local
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "{{ .Values.kafka.host }}:9092"
        image: provectuslabs/kafka-ui
        name: kafka-ui
        ports:
        - containerPort: 80
          name: http1
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 0
      securityContext: 
        runAsUser: 0
      serviceAccount: {{ .Release.Namespace }}-getapp-run-as-root
      serviceAccountName: {{ .Release.Namespace }}-getapp-run-as-root
