{{- if (include "infra.enabled" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-kube-state-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-kube-state-metrics
  namespace: {{ .Release.Namespace }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-kube-state-metrics
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:kube-state-metrics
        name: kube-state-metrics
        args:
        - --resources=pods
        - '--namespaces={{ .Release.Namespace }}'
      serviceAccount: {{ .Release.Name }}-run-as-root
      serviceAccountName: {{ .Release.Name }}-run-as-root

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kube-state-metrics
  namespace: kube-system
  labels:
    app: kube-state-metrics
spec:
  selector:
    app: kube-state-metrics
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: telemetry
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
{{- end }}
