{{- if (include "infra.enabled" .) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: loki-config
data:
  loki.yaml: |
    server:
      http_listen_port: 3100

    common:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - loki-memberlist

    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h
    
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    
    compactor:
      working_directory: /data/loki/compactor
      shared_store: filesystem
      compaction_interval: 30m
    
    chunk_store_config:
      max_look_back_period: 720h
    
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h
    
    limits_config:
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 24
      max_concurrent_tail_requests: 20

    auth_enabled: false
{{- end }}