apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promtail-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promtail-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: promtail-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: promtail-role
  apiGroup: rbac.authorization.k8s.io