version: '3.6'
services:
  api:
    container_name: api
    image: harbor.getapp.sh/getapp-dev/api:1.2.48
    # image: harbor.getapp.sh/getapp-dev/api:${API_TAG}
    restart: always
    env_file:
      - .env.dev
    networks:
      - getapp
    ports:
      - 3000:3000

  upload:
    container_name: upload
    image: harbor.getapp.sh/getapp-dev/upload:1.1.22
    # image: harbor.getapp.sh/getapp-dev/upload:${UPLOAD_TAG}
    restart: always
    env_file:
      - .env.dev
    networks:
      - getapp

  discovery:
    container_name: discovery
    image: harbor.getapp.sh/getapp-dev/discovery:1.1.41
    # image: harbor.getapp.sh/getapp-dev/discovery:${DISCOVERY_TAG}
    restart: always
    env_file:
      - .env.dev
    networks:
      - getapp

  offering:
    container_name: offering
    image: harbor.getapp.sh/getapp-dev/offering:1.1.28
    # image: harbor.getapp.sh/getapp-dev/offering:${OFFERING_TAG}
    restart: always
    env_file:
      - .env.dev
    networks:
      - getapp

  delivery:
    container_name: delivery
    image: harbor.getapp.sh/getapp-dev/delivery:1.1.45
    # image: harbor.getapp.sh/getapp-dev/delivery:${DELIVERY_TAG}
    restart: always
    env_file:
      - .env.dev
    environment:
      USE_CACHE: 'true'
      USE_MAP_CACHE: 'true'
    networks:
      - getapp

  deploy:
    container_name: deploy
    image: harbor.getapp.sh/getapp-dev/deploy:1.1.28
    # image: harbor.getapp.sh/getapp-dev/deploy:${DEPLOY_TAG}
    restart: always
    env_file:
      - .env.dev
    networks:
      - getapp

  project-management:
    container_name: project-management
    image: harbor.getapp.sh/getapp-dev/project-managment:1.1.15
    # image: harbor.getapp.sh/getapp-dev/project-management:${PROJECT_MANAGMENT_TAG}
    restart: always
    env_file:
      - .env.dev
    networks:
      - getapp

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    networks:
      - getapp
    environment:
      KAFKA_CLUSTERS_0_NAME: broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      DYNAMIC_CONFIG_ENABLED: 'true'

  broker:
    image: confluentinc/cp-kafka:7.4.1
    hostname: broker
    container_name: broker
    networks:
        - getapp
    ports:
    - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://getapp-test.getapp.sh:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NUM_PARTITIONS: "5"


  pg:
    container_name: postgres
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: J3-X}plSnqw5M~c
      POSTGRES_DB: get_app
    ports:
      - 5432:5432
    networks:
      - getapp
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  getmap-node:
    image: harbor.getapp.sh/getapp-dev/getmap-node:1.0.52
    restart: always
    env_file:
      - .env.dev
    environment:
      LIBOT_EXPORT_URL: https://export-management-export-management-route-integration.apps.j1lk3njp.eastus.aroapp.io/api/raster/v1/export-tasks
      LIBOT_DISCOVERY_URL: https://raster-pycsw-int-nginx-route-integration.apps.j1lk3njp.eastus.aroapp.io/api/raster/v1\
      LIBOT_CALLBACK_URL: http://getapp-test.getapp.sh:3000/api/map/export-notification
      TOKEN_LIBOT: "eyJhbGciOiJSUzI1NiIsImtpZCI6Im1hcC1jb2xvbmllcy1pbnQifQ.eyJkIjpbInJhc3RlciIsInJhc3RlckV4cG9ydCJdLCJpYXQiOjE2NzYyMTQ5NzIsInN1YiI6ImdldE1hcEN1c3RvbWVyIiwiaXNzIjoibWFwY29sb25pZXMtdG9rZW4tY2xpIn0.TYqpoyw_s1JXoELi2k2wGJ3vEvlt3JH5KexGOeKPKeBWWVMVUkXnU0pDJSMLRNwLvlnkEa0hRT2Ktw9bVcL5lVytHR4Yex_8Tv0EA1RQyrcQ-MndumuwI4O6-6dqI5iGAmd6SAhBSP3cOkdsYDhRz_IT4ZQrqmN17Lty9UfQNEGLJnsH-egc8aQKe3iGas8G5uZE8QlQJkw8k9HMObSk1J70IHmp75S1JEZ3Jvk0fymaeVyAuh1_TLixOPoVFc65vGti2uplMRiylsZNxPML1fAHcLWVZP_VnB_IbcGKiHeWWTxJmVruV6iANCFSiQI8S1GnyA15afJbKZw5ByTAIg"
      MC_CSW_REF_DATE: "2023-10-15T00:00:01Z"
      TARGET_RESOLUTION: '17'
      MC_MIN_RESOLUTION_DEG: "4.29153E-05"
      MC_MAX_RESOLUTION_DEG: "1.34110E-06"
      # UPDATE_GOB_TIME: '0 */5 * * * *'
      UPDATE_GOB_TIME: '0 0 */6 * * *'

    # ports:
    #   - 8000:3000
    networks:
      - getapp

  dashboard:
    container_name: dashboard
    image: harbor.getapp.sh/getapp-dev/dashboard:1.2.12
    restart: always
    env_file:
      - .env.production
    # networks:
    #   - getapp
    ports:
      - 3002:3002
    command: sh -c "npm run build && npm run start"


networks:
  getapp:
    driver: bridge
