apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: uptime-kuma
  labels:
    getapp: uptime-kuma
    gitlabrelease: "{{ .Values.gitlabrelease }}"
spec:
  host: uptime-kuma-{{ .Values.routePrefix }}.{{ .Values.routeMainlUrl }}
  to:
    kind: Service
    name: uptime-kuma
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
