apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  labels:
    getapp: discovery
    chart: {{ template "getapp-api.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    gitlabrelease: "{{ .Values.gitlabrelease }}"
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      getapp: discovery
  template:
    metadata:
      labels:
        getapp: discovery
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
      serviceAccountName: getapp-run-as-root
      containers:
        - name: discovery
          image: "{{ .Values.repository }}discovery:{{ .Values.tag.discovery }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 500m
              memory: 300Mi
          ports:
            - name: http3
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          envFrom:
            - configMapRef:
                name: "getapp-{{ .Values.configmap }}"
          # env:
          #   - name: POSTGRES_PASSWORD   # Name of the environment variable
          #     valueFrom:
          #       secretKeyRef:
          #         name: "postgres-{{ .Values.configmap }}-pguser-postgres-{{ .Values.configmap }}"
          #         key: password
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

