image:
  pullPolicy: IfNotPresent
  repository: harbor.getapp.sh/getapp-dev/

kafka:
  host: kafka-service
  port: 9092

tag:
  api: 1.3.95-develop
  delivery: 1.3.71-develop
  deploy: 1.3.41-develop
  discovery: 1.3.92-develop
  offering: 1.3.69-develop
  projectmanagment: 1.3.35-develop
  upload: 1.3.41-develop
  dashboard: 1.3.8-develop
  search: 1.3.41-develop

replicaCount: 1
configmap: getapp-f
routePrefix: getapp-f
routeMainlUrl: apps.sr.eastus.aroapp.io
dbName: getapp-f
gitlabrelease: 1.3.39

deployment:
  containerPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

probes:
  enabled: true
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: getapp-f.apps.sr.eastus.aroapp.io
      paths:
        - path: /
          pathType: Prefix

# Infrastructure Stack Configuration
infraStack:
  enabled: false  # Set to false to temporarily disable all infra-stack components
