getapp-api:
  fullnameOverride: getapp-api

#--------------------------------------------------------------------------------
# values from the "variables" section in gilab_ci.yml in this repository
#--------------------------------------------------------------------------------

  replicaCount: 
  configmap: 
  routePrefix: 
  routeMainlUrl: apps.sr.eastus.aroapp.io
  dbName: 
  webProtocol: https://
#--------------------------------------------------------------------------------
#
# the values of the variables in this section are generaited from the .env file, 
# that is created in this pipeline: 
# https://gitlab.getapp.sh/getapp/Main-version-control/getapp-release-versions/-/blob/master/.gitlab-ci.yml
#
#--------------------------------------------------------------------------------
  gitlabrelease: 1.3.25
  repository: harbor.getapp.sh/getapp-dev/
  tag:
    api: 1.3.87-develop
    delivery: 1.3.71-develop
    deploy: 1.3.41-develop
    discovery: 1.3.92-develop
    offering: 1.3.69-develop
    projectmanagment: 1.3.35-develop
    upload: 1.3.41-develop
    dashboard: 1.3.8-develop
    getmap: 1.3.59-develop
    docs: v1-27-01-2025
  namespace:
      openshiftProjectName: 


#--------------------------------------------------------------------------------
# END
#--------------------------------------------------------------------------------

  image:
    repository: harbor.getapp.sh/getapp-dev/api
    tag: 1.0.68
    pullPolicy: IfNotPresent
  imagePullSecrets: 
    # Optionally specify an array of imagePullSecrets.
    # Secrets must be manually created in the namespace.
    # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
    #
    # This uses credentials from secret "myRegistryKeySecretName".
    - name: harbor-registry-secret

  service:
    type: ClusterIP 
    port: 80
  deployment:
    containerPort: 80
  probes:
    enabled: false
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/tls-acme: "true"
    path: /
    # hosts:
    #   - chart-example.local
    tls: []
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local
  secrets: {{VAR}}
    # Optionally specify a set of secret objects whose values
    # will be injected as environment variables by default.
    # You should add this section to a file like secrets.yaml
    # that is explicitly NOT committed to source code control
    # and then include it as part of your helm install step.
    # ref: https://kubernetes.io/docs/concepts/configuration/secret/
    #
    # This creates a secret "mysecret" and injects "mypassword"
    # as the environment variable mysecret_mypassword=password.
    # mysecret:
    #   mypassword: password
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Service-specific env vars: 
  #serviceEnvVars:
  #  - name: AUTH_SERVER_URL 
  #    value: https://keycloak.getapp.sh/auth
