apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      serviceAccountName: {{ .Release.Namespace }}-getapp-run-as-root
      containers:
      - name: loki
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: grafana/loki:2.9.2
        args:
        - -config.file=/etc/loki/config/loki.yaml
        - -config.expand-env=true
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 7946
          name: memberlist
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/loki/config
        # - name: storage
        #   mountPath: /data/loki
        # resources:
        #   requests:
        #     cpu: 500m
        #     memory: 512Mi
        #   limits:
        #     cpu: 1
        #     memory: 1Gi
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 45
          periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: loki-config
            # items:
            #   - key: config.yaml
            #     path: config.yaml
        # - name: storage
        #   persistentVolumeClaim:
        #     claimName: loki-storage

