{{- if (include "infra.enabled" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matomo
  name: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: APACHE_HTTP_PORT_NUMBER
          value: "8080"
        - name: APACHE_HTTPS_PORT_NUMBER
          value: "8443"
        - name: MATOMO_DATABASE_HOST
          value: mariadb
        - name: MATOMO_DATABASE_PORT_NUMBER
          value: "3306"
        - name: MATOMO_DATABASE_NAME
          value: bitnami_matomo
        - name: MATOMO_DATABASE_USER
          value: bn_matomo
        - name: MATOMO_DATABASE_PASSWORD
          value: Herr$Owejpynd5
        - name: MATOMO_SKIP_BOOTSTRAP
          value: "no"
        - name: MATOMO_USERNAME
          value: user
        - name: MATOMO_PASSWORD
          value: Be!QuiTril0
        - name: MATOMO_EMAIL
          value: user@example.com
        - name: MATOMO_WEBSITE_NAME
          value: example
        - name: MATOMO_WEBSITE_HOST
          value: https://example.org
        - name: MATOMO_TRACKER_TRACKING_REQUESTS_REQUIRE_AUTHENTICATION_WHEN_CUSTOM_TIMESTAMP_NEWER_THAN
          value: "2592000"
        image: docker.io/bitnami/matomo:5.0.2-debian-12-r4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /matomo.php
            port: http
            scheme: HTTP
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: matomo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /matomo.php
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /bitnami/matomo
          name: matomo-data
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - status.localhost
        ip: 127.0.0.1
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
      volumes:
      - name: matomo-data
        persistentVolumeClaim:
          claimName: matomo
{{- end }}