{{- if (include "infra.enabled" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptimekuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        # Main Uptime Kuma container
        - name: uptimekuma
          image: louislam/uptime-kuma:latest
          ports:
            - containerPort: 3001
        #   volumeMounts:
        #     - name: uptimekuma-data
        #       mountPath: /app/data
        # Sidecar container for database initialization
        - name: db-initializer
          image: node:18
          command: ["sh", "-c"]
          args:
            - |
              until [ -f /app/data/kuma.db ]; do
                echo "Waiting for Uptime Kuma to create the database..."
                sleep 5
              done
              echo "Database detected. Checking contents..."
              node /scripts/setup-uptime-kuma-db.js
          volumeMounts:
            - name: uptimekuma-data
              mountPath: /app/data
            - name: init-script
              mountPath: /scripts
      volumes:
        - name: uptimekuma-data
          emptyDir: {}
        #   persistentVolumeClaim:
        #     claimName: uptimekuma-data
        - name: init-script
          configMap:
            name: uptimekuma-init-script
      serviceAccount: {{ .Release.Namespace }}-getapp-run-as-root
      serviceAccountName: {{ .Release.Namespace }}-getapp-run-as-root
{{- end }}