{{- if (include "infra.enabled" .) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}