{{- if (include "infra.enabled" .) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: uptime-kuma
    openshift.io/cluster-monitoring: "true"
  name: uptime-kuma
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: uptime-kuma
  type: ClusterIP
{{- end }}