getapp-api:
  fullnameOverride: getapp-api

#--------------------------------------------------------------------------------
# values from the "variables" section in gilab_ci.yml in this repository
#--------------------------------------------------------------------------------

  replicaCount: 1
  configmap: getapp-ci
  routePrefix: getapp-ci
  routeMainlUrl: apps.sr.eastus.aroapp.io
  dbName: getapp-ci

#--------------------------------------------------------------------------------
#
# the values of the variables in this section are generaited from the .env file, 
# that is created in this pipeline: 
# https://gitlab.getapp.sh/getapp/Main-version-control/getapp-release-versions/-/blob/master/.gitlab-ci.yml
#
#--------------------------------------------------------------------------------
  gitlabrelease: 1.3.43
  repository: harbor.getapp.sh/getapp-ci/
  tag:
    api: 1.3.95-develop
    delivery: 1.3.71-develop
    deploy: 1.3.41-develop
    discovery: 1.3.92-develop
    offering: 1.3.69-develop
    projectmanagment: 1.3.35-develop
    upload: 1.3.41-develop
    dashboard: 1.3.8-develop
    getmap: 1.3.59-develop
    docs: v1-27-01-2025
  namespace:
      openshiftProjectName: getapp-ci


#--------------------------------------------------------------------------------
# END
#--------------------------------------------------------------------------------

  image:
    repository: harbor.getapp.sh/getapp-ci/
    pullPolicy: IfNotPresent #Always

  service:
    type: ClusterIP 
    port: 80
  deployment:
    containerPort: 80
  probes:
    enabled: false
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/tls-acme: "true"
    path: /
    # hosts:
    #   - chart-example.local
    tls: []
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local
  kafka:
    host: kafka
    port: 9092

# Infrastructure Stack Configuration
infra-stack:
  enabled: false  # Set to false to temporarily exclude infra-stack