apiVersion: v1
kind: ConfigMap
metadata:
  name: "getapp-{{ .Values.configmap }}"
  labels:
    getapp: api
    chart: {{ template "getapp-api.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    gitlabrelease: "{{ .Values.gitlabrelease }}"

data:
  # Keycloak
  AUTH_SERVER_URL: "https://keycloak.getapp.sh/auth"
  REALM: "getapp"
  CLIENT_ID: "api"
  SECRET_KEY: "2SmS4ldaAxTJRyFBGPuJWvEgtG4oqyPm"
  COOKIE_KEY: "KEYCLOAK_JWT"

  # Kafka
  KAFKA_BROKER_URL: "kafka-broker-service.{{ .Values.configmap }}.svc.cluster.local:9092"
  KAFKAJS_NO_PARTITIONER_WARNING: "1"

  # Microservice client
  MICRO_SERVICE_TYPE: "KAFKA" #KAFKA/SOCKET
  MICROSERVICE_RESPONSE_WAIT_TIME: "10000"

  # Postgres
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "getapp"
  POSTGRES_PASSWORD: "Fw|G0f>r(;;p{cyQ:{_8-N.5"
  POSTGRES_DB: "getapp"

  #gFrogArtifactory
  JFROG_BASE_URL: "http://getapp-dev.getapp.sh:8082/artifactory/"
  JFROG_REPO: "getapp-test/"
  JFROG_USER_NAME: "admin"
  JFROG_PASSWORD: "Get!1@2App&map"

  DEVICE_SECRET: DEVICE_SECRET
  # JWT
  JWT_SECRET: "this-is-my-secret-only-for-dev"
  JWT_EXPIRATION: "100y"

  # AWS
  AWS_REGION: "us-east-2"
  ACCESS_KEY_ID: "AKIA2SUDFN5CC2BHCCQG"
  SECRET_ACCESS_KEY: "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"
  BUCKET_NAME: "getapp-develop"
  UPLOAD_URL_EXPIRE: "3600" # seconds
  DOWNLOAD_URL_EXPIRE: "3600"

  # integration test envs
  SERVER_URL: "api-{{ .Values.routePrefix }}.{{ .Values.routeMainlUrl }}/api/"
  TEST_USERNAME: "rony@example.com"
  TEST_PASSWORD: "rony123"
  COMPONENT_NAME: "test-demo"
  COMPONENT_DESCRIPTION: "Description demo"
  RELEASE_NOTE: "some notes"
  MIGRATION_RUN: 'true'
  PRODUCT_ID: "3a924ad6-6565-4112-b0b7-9f91cd6adc99"
  BOUNDING_BOX: "34.66110229026526,31.827201840060297,34.67849731678143,31.84703826875193"
