name: Upload to Azure and Get Download Link

on:
  push:
    branches:
      - main

jobs:
  upload-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create a text file
      run: echo "This is a simple text file." > simple.txt

    - name: Zip the text file
      run: zip simple.zip simple.txt

    - name: Upload file to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --account-key $AZURE_STORAGE_KEY \
            --container-name $AZURE_CONTAINER \
            --file simple.zip \
            --name simple.zip
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}

    - name: Generate Download Link
      id: get-link
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}
      run: |
        echo "https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${AZURE_CONTAINER}/simple.zip" > download_link.txt
        cat download_link.txt
